### ISSUE TITLE
predix.py error

### ISSUE THREAD

**Issue by AllanGottigNovotek** [PredixDev/predix-rmd-ref-app#11]
Hi
The installer crashes when I install the RMD.
It looks like it fails when it sets some service to receive data.
Maybe my account do not have access to the data source?
user: Allan.Gottig(at)novotek.com

Please see attached log.
Look forward playing with Predix the next many years.

Best
Allan
[log.txt](https://github.com/PredixDev/predix-rmd-ref-app/files/325680/log.txt)

**Comment by gstroup** [comment]
Hi Allan,

Looks like it failed connecting to artifactory to download a jar file.  Not sure why that happened.  We are actually in the process of pushing out an updated version of the ref app today.  I would recommend trying a fresh checkout tomorrow.  If you still have problems, let us know.

Thanks.

   -Greg

**Comment by AllanGottigNovotek** [comment]
Hi Greg
Same error. 
I did:
-	rm predix-rmd-ref-app 
-	git clone.....
BTW:
The folder "..ref-app/data-seed-.../target" is empty.
Should there not be a .jar file before it push the Predix?

I use the devBox Linux environment.
No rush, I am just playing and try to learn.
[logAfterUpdate_20160623.txt](https://github.com/PredixDev/predix-rmd-ref-app/files/329509/logAfterUpdate_20160623.txt)

**Comment by gstroup** [comment]
Hmm... seems like you're having problems connecting to artifactory.  That's probably why the jar file is missing.  Can you check your maven settings.xml file, and make sure you can access artifactory?

**Comment by turnerth** [comment]
we have a jenkins job that runs this every 2 hours and is succeeding, so, could you redownload and try again?  Please ensure you've set your encrypted password in the ~/.m2/settings.xml and if you are accessing the cloud through a network proxy be sure to set the env vars for proxy.  Both are mentioned in the setup instructions of the tutorial.

I really think the missing predix.io password in ~/.m2/settings.xml is your problem
