### ISSUE TITLE
python build error: com.ge.predix.solsvc:rmd-ref-app

### ISSUE THREAD

**Issue by hanwsf** [PredixDev/predix-rmd-ref-app#12]
[ERROR]   
[ERROR]   The project com.ge.predix.solsvc:rmd-ref-app:1.0.10 (/predix/predix-rmd-ref-app/pom.xml) has 1 error
[ERROR]     Child module /predix/predix-rmd-ref-app/predix-microservice-cf-spring/pom.xml of /predix/predix-rmd-ref-app/pom.xml does not exist
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
Maven build failed.
Traceback (most recent call last):
  File "/predix/predix-rmd-ref-app/scripts/refApp.py", line 89, in buildReferenceApp
    sys.exit(1);
SystemExit: 1
None
()

**Comment by turnerth** [comment]
we have a jenkins job that runs this every 2 hours.  so, could you redownload and try again?  Please ensure you've set your encrypted password in the ~/.m2/settings.xml and if you are accessing the cloud through a network proxy be sure to set the env vars for proxy.  Both are mentioned in the setup instructions of the tutorial.
