### ISSUE TITLE
Win and Devbox compiling issue

### ISSUE THREAD

**Issue by hanwsf** [PredixDev/predix-rmd-ref-app#13]
In Win7, it will fail at data service.
In Devbox, it will fail as the test of fdh-router-cf cause the authentication in the  manifest is not accessible, only disabling the test in refapp.py can make it success. It works, but the meters are undefined.

**Comment by gstroup** [comment]
Hmm... we have automated CI builds running on Windows and Linux.  Both are passing now.  Can you pull the latest code and try again?

**Comment by turnerth** [comment]
How did it go?  Did you try again?  Might have been a cloud issue that day.  Closing for now.
