### ISSUE TITLE
rmd_asset not found

### ISSUE THREAD

**Issue by Dev79** [PredixDev/predix-rmd-ref-app#14]
I'm trying to run python scripts/installRefApp.py for thr rmd-sample app and i'm getting the error:
rmd_asset not found

followed by the execption error:
Exception when running deployRefAppDelete.

Many thanks in adavance for the help

**Comment by turnerth** [comment]
there's a new version today.  you can redownload and try.  Suggest your earlier problem was related to an inability to delete services or apps.  You may need to clean it manually before running the script.
