### ISSUE TITLE
nginx to nodejs/express migration

### ISSUE THREAD

**Issue by PiotrekPaprocki** [PredixDev/predix-rmd-ref-app#16]
Hi.

Do you plan to migrate nginx to node/express in rmd-ref-app-ui? nginx is causing some problems many teams are struggling. Do you plan to make a migration guide?
Thanks.

**Comment by gstroup** [comment]
Yes, we do plan to migrate the rmd-ref-app-ui project to use NodeJS & Express.  It's on our backlog.  We have been focusing on cleaning up the predix-seed app first.  Watch the predix-seed app for a release coming very soon, that will greatly simplify that application, switching to Polymer and Express.  The Express app will be very similar to NodeJS starter.  You can get a preview by looking at this branch:  https://github.com/PredixDev/predix-seed/tree/polymer-only

**Comment by turnerth** [comment]
closing since this was implemented
