### ISSUE TITLE
rmd-ref-app with existing services

### ISSUE THREAD

**Issue by sebastianroming** [PredixDev/predix-rmd-ref-app#19]
Is it possible to deploy the predix-rmd-ref-app and bind to existing Services (UAA, Asset, Timeseries...) ? 

I don't know if the deployment will fail when I change the variables in `refAppConfig.py`.

**Comment by turnerth** [comment]
um, it should.  The ref-app python script, analytics-ref-app python script and quickstart.sh script all re-use the same UAA, Asset, Timeseries.

**Comment by sebastianroming** [comment]
@turnerth What does CF do if the `cf cs` command is submitted to a service that already exists?

**Comment by gstroup** [comment]
You can create multiple instances of a service with the `cf cs` command.  But each instance must have a unique name.

**Comment by turnerth** [comment]
it 'fails', in the sense that it does nothing because it already exists.
