### ISSUE TITLE
RMD REF App not working

### ISSUE THREAD

**Issue by 17100106** [PredixDev/predix-rmd-ref-app#25]
Hi I installed the predix rmd-ref-app using Devbox and there was no error. It showed build success. It gave me a url (to show the front end) at the end which also works but when I set the refresh frequency to 3 seconds or a different number, it doesnt work and the values do not get updated. Any help would be greatly appreciated. Thank you!

**Comment by turnerth** [comment]
We turn the data simulator on for 30 seconds in the install script.  In order to avoid filling up Predix with not-needed time series data we turn off the simulator.

Please start the xxxx-data-exchange-simulator app.

**Comment by 17100106** [comment]
When I try to start the data exchange simulator app, it fails and shows that the app is not found. Can you help me with this? Thank you

**Comment by gstroup** [comment]
Run the `cf a` command to see the list of apps.  Then `cf start` the simulator app.  Also, you may need to restart the websocket server to see the "live data".

**Comment by 17100106** [comment]
Yes that worked. Thank you so much!
