### ISSUE TITLE
Movement of data from the simulator to the dashboard display

### ISSUE THREAD

**Issue by 17100106** [PredixDev/predix-rmd-ref-app#26]
I am having problems understanding how data moves from the data-exchange-simulator app to the front end dashboard display. I looked at the scripts for the data-exchange-simulator and from what I understand it writes them to a file and the front end reads it from there. Is this correct? If yes, how can I look at this file that is made? Thank you!

**Comment by turnerth** [comment]
The simulator creates data inside of a Java Microservice.  It hands it to the Data Exchange rest endpoint. 

It then gets translated to Predix Time Series and using the java Time Series SDK sends it over Secure Web Sockets.  The Data Exchange also gives the simulated data to a Web Socket Server.  

The Reference App then requests data in two ways.  From the RMD Datasource which queries Predix Asset and gets the Time Series tags from the asset model.  It then uses the same Java Time Series SDK to retrieve the data from the rest endpoint.

The 2nd way is via a live data feed via the Web Socket Server.

**Comment by 17100106** [comment]
Oh okay thanks a lot! Will it be possible that you tell me the name of the scripts where all this is happening? Would appreciate it a lot!

**Comment by turnerth** [comment]
There is a quickstart script that installs all that.
https://github.com/PredixDev/predix-rmd-ref-app/blob/master/scripts/quickstart-rmd-ref-app.sh

But at runtime it's a set of Microservices that call each other in the way mentioned.  You just start the Simulator microservice and it calls the Rest endpoint of the running Data Exchange microservice.
