### ISSUE TITLE
Predix RMD-REF-ANALYTICS-APP not working

### ISSUE THREAD

**Issue by 17100106** [PredixDev/predix-rmd-ref-app#27]
Hello, I have installed the Predix rmd-ref-app and when I turn the data simulator on, the readings on the dashboard start changing. Now I wanted to try out the analytics part and so I installed the rmd-ref-analytics-app. I've turned the data simulator on again but I dont really see any analytics on the dashboard. How do I see analytics being run on the data that is coming in? Thank you

**Comment by gstroup** [comment]
Right now, you won't see any advanced analytics.  You should see the same values, however now the red/green status of the rows in the data table should be calculated by a simple "analytic" running in the Predix Analytic framework.  It's a simple example, just showing how to connect the different pieces of Predix into a cohesive application.

**Comment by 17100106** [comment]
Oh okay. Thank you so much! You were very helpful. Could you tell me how I could build a digital twin using predix? As in the 3D model that they advertise. Thank you

**Comment by 17100106** [comment]
Just a follow up question, can I find out what analytic is running in the Predix Analytic framework?

**Comment by turnerth** [comment]
suggest you read the Predix Docs about the Analytic Framework.
