### ISSUE TITLE
Asset service is failing

### ISSUE THREAD

**Issue by LarissaLeal** [PredixDev/predix-rmd-ref-app#28]
I am trynig to Install the RMD Reference App running bash <(curl https://raw.githubusercontent.com/PredixDev/predix-rmd-ref-app/master/scripts/quickstart-rmd-ref-app.sh ) --skip-setup
But when was creating Asset Service Instance failed.

**Comment by turnerth** [comment]
Can you provide more info?  It's hard to say what the problem might be.

**Comment by LarissaLeal** [comment]
The error is that: 
FAILED
Failed to fetch target UAA's info
-->> Couldn't create Predix Asset service. Retrying...

FAILED
Failed to fetch target UAA's info
**************** Error Occurred ***************************
Failure to run quickstart script
View logs at /predix/rmd-ref-app/predix-scripts/log/quickstartlog.log
***********************************************************
**************** Stack Trace ****************************
149 __try_create_predix_service /predix/rmd-ref-app/predix-scripts/bash/scripts/predix_funcs.sh
143 createAssetService /predix/rmd-ref-app/predix-scripts/bash/scripts/predix_services_setup.sh
321 __setupServices /predix/rmd-ref-app/predix-scripts/bash/scripts/predix_services_setup.sh
184 source predix-scripts/bash/quickstart.sh
120 main /dev/fd/63

Couldn't create Predix Asset service instance... /predix/rmd-ref-app/predix-scripts/log

**Comment by turnerth** [comment]
I just ran the script and it completed.  I did have to run it twice because an error occurred somewhere between the script and the cloud or in the cloud.  But the problem didn't seem to be with the script itself.   

If you re-run it and it fails, please attach the whole output in a file so we can see if something up above failed.

**Comment by turnerth** [comment]
I see the smoke test is working so closing this.
