### ISSUE TITLE
Build Fails, - Could not find plan with name Tiered when creating uaa service instance

### ISSUE THREAD

**Issue by p021918** [PredixDev/predix-rmd-ref-app#4]
I try to push a Starter Pack - predix-rmd-ref-app and got failed as below; attached  the whole message as detail. . Please advise. Many thanks

[Predix-RMD-REF-App.docx](https://github.com/PredixDev/predix-rmd-ref-app/files/140340/Predix-RMD-REF-App.docx)

---------------------------------------------------------------
cf cs predix-uaa Tiered rmd_uaa_kyehyun_park -c /predix/predix-rmd-ref-app/uaa_payload.json
Creating service instance rmd_uaa_kyehyun_park in org predix-adoption / space training2 as kyehyun.park@ge.com...
FAILED
Could not find plan with name Tiered
Traceback (most recent call last):
  File "/predix/predix-rmd-ref-app/scripts/refApp.py", line 736, in deployReferenceAppCreateUAA
    createPredixUAASecurityService(config)
  File "/predix/predix-rmd-ref-app/scripts/refApp.py", line 117, in createPredixUAASecurityService
    sys.exit("Error creating a uaa service instance")
SystemExit: Error creating a uaa service instance
None
()

**Comment by gstroup** [comment]
This looks like a transient problem that happened with the UAA service.  The plan name "Tiered" is correct.  Are you in Predix Basic (VPC) or Select (ASV)?  If you run the command `cf m` do you see the UAA service with plan name "Tiered"?  You can try running the installRefApp.py script again, and it should work.

**Comment by p021918** [comment]
cf m, i see basic and free, not Tiered.
I am training2 space under predix-adoption  org.Please advise how to check where I am in (VPC or ASV?) 
-------------------------------------
API endpoint:   https://api.grc-apps.svc.ice.ge.com (API version: 2.48.0)   
User:           kyehyun.park@ge.com   
Org:            predix-adoption   
Space:          training2   
-----------------------------------------

**Comment by gstroup** [comment]
Oh, I see you're on an internal CF space, not intended for customers to use for app development.  The install script won't work here.  Please go to https://predix.io, and register for a free trial account.  Then you'll be in the VPC environment, and the install script will work.

**Comment by turnerth** [comment]
Oh, FYI...we'll be removing everyone from that training space.

**Comment by p021918** [comment]
thanks, now i am able to run the script on production space of mine. but I have faced another issues starting from below: For the helps, I have attached full message I got. Many thanks
[Predix-RMD-REF-App - run script errors.docx](https://github.com/PredixDev/predix-rmd-ref-app/files/143586/Predix-RMD-REF-App.-.run.script.errors.docx)


FAILED
Could not find a default domain
Traceback (most recent call last):
  File "/predix/predix-rmd-ref-app/scripts/refApp.py", line 739, in deployReferenceAppCreateUAA
    deployAndBindUAAToPredixBoot(config)
  File "/predix/predix-rmd-ref-app/scripts/refApp.py", line 161, in deployAndBindUAAToPredixBoot
    deployProject('cf push '+config.predixbootAppName+' -f '+'predix-microservice-cf-jsr/manifest.yml',config.predixbootJSRRepoName)
  File "/predix/predix-rmd-ref-app/scripts/refApp.py", line 26, in deployProject
    sys.exit("Error deploying the project"+projectDir)

**Comment by turnerth** [comment]
looking in your word doc.  this is the error.  I think there was an ACS error in the cloud.  Please run it again today.

SystemExit: unable to upload Asset Data using curl in deployReferenceAppCreateDataseed, output={"status":500,"error":"Internal Server Error","message":"error=\"invalid_request\", error_description=\"Forbidden\", message=\"Access is denied\", status=\"403\""} curl=curl -F "username=rmd_admin_1" -F "password=RMD_admin_1" -F "file=@./data-seed-service/src/main/resources/rmdapp/AssetData.xls"  https://data-seed-kyehyun-park.run.aws-usw02-pr.ice.predix.io/uploadAssetData

**Comment by p021918** [comment]
thanks, I re-run from new space. It moved  and is issuing new error as below.
...................................
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project fdh-asset-handler: There are test failures.
[ERROR] 
[ERROR] Please refer to /predix/predix-rmd-ref-app/fdh-router-service/fdh-asset-handler/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :fdh-asset-handler
Maven build failed.
Traceback (most recent call last):
  File "/predix/predix-rmd-ref-app/scripts/refApp.py", line 692, in buildReferenceApp
    sys.exit(1);
SystemExit: 1
None
()
Exception when running buildReferenceApp.  Retrying
[Predix-RMD-REF-App - run script errors 0225.docx](https://github.com/PredixDev/predix-rmd-ref-app/files/146052/Predix-RMD-REF-App.-.run.script.errors.0225.docx)

Pulling Submodules

**Comment by p021918** [comment]
i got git clone again with the one uploaded on Feb 23 and built success. Many thanks.
