### ISSUE TITLE
Not able to run installRefApp.py script on windows machine.

### ISSUE THREAD

**Issue by priyabandaru** [PredixDev/predix-rmd-ref-app#5]
Getting the below error  on windows machine . 
****************** Installing Reference Application ******************

Setting Redis config.predixRedis as redis-1

Setting Redis config.predixRedis as redis-5

Pulling Submodules

fatal: Not a git repository (or any of the parent directories): .git

fatal: Not a git repository (or any of the parent directories): .git

Build using maven setting : ~/.m2/settings.xml Maven Repo :

[ERROR] Error executing Maven.

[ERROR] The specified user settings file does not exist: D:\Predix20\Samples\predix-rmd-app\new\predix-rmd-ref-app-master\scripts\~\.m2\settings.xml

Maven build failed.

**Comment by dianezhen** [comment]
priyabandaru,

  I think the install scripts are geared towards a *nix type platform, I had this same issue.  I updated the scripts/refAppConfig.py script and changed line 69 'mvnsettings = '  to point to my user windows user directory specifically (eg C:/Users/<SSO>/.m2/settings.xml).  It then worked for me.

Diane

**Comment by priyabandaru** [comment]
Thanks Diane , I will make that change. There are also windows user and they will face this issue .

**Comment by dianezhen** [comment]
priyabandaru,  agreed.  This concern has also been noted on the predix forum.

**Comment by wushu123** [comment]
Thanks for letting us know. 
please use the install script as follows:

python installRefApp.py -s <your maven user settings file>

I will update when the fix will be patched or released. 

thanks.

**Comment by wushu123** [comment]
the commandline usage is broken in my previous post:

python installRefApp.py -s maven-settings-xml-file-goes-here

**Comment by priyabandaru** [comment]
I will update the user about this option . Thank you

**Comment by gstroup** [comment]
windows users need cygwin for now.

**Comment by turnerth** [comment]
we just tested the latest version on windows and it's running fine.  We now recommend to use git-bash on windows and will be updating tutorials to state that.
