### ISSUE TITLE
DataIngestionServiceController : Unable to Save data from machinedata_simulator

### ISSUE THREAD

**Issue by indaco** [PredixDev/predix-rmd-ref-app#6]
after a successful deployment of the rmd-ref-app, I simply do `cf start machinedata_simulator_my_name`. Nothing configured by me

This is the manifest file content

```
applications:
  - name: machinedata_simulator_my_name
    buildpack: java_buildpack
    path: target/machinedata-simulator-1.1.4.jar
    timeout: 120
env:
    machineControllerId: 1
    predix_dataingestion_service_uri: https://dataingestion-service-my_name.run.aws-usw02-pr.ice.predix.io
```

the machinedata_simular send data correctly to the dataingestion service. There, seems that there is some problem for the data ingestion service to send data to the time_series service

```
OUT 2016-03-17 17:57:07.300 ERROR 29 --- [o-63575-exec-10] g.p.s.d.s.DataIngestionServiceController : Unable to Save [{"name":"Compressor-2015:CompressionRatio","unit":"1","register":"","datatype":"DOUBLE","value":13447.15600771321,"timestamp":1458237427279},{"name":"Compressor-2015:DischargePressure","unit":"1","register":"","datatype":"DOUBLE","value":13030.080993269079,"timestamp":1458237427279},{"name":"Compressor-2015:SuctionPressure","unit":"1","register":"","datatype":"DOUBLE","value":4.834145291210089,"timestamp":1458237427279},{"name":"Compressor-2015:MaximumPressure","unit":"1","register":"","datatype":"DOUBLE","value":14569.623872065262,"timestamp":1458237427279},{"name":"Compressor-2015:MinimumPressure","unit":"1","register":"","datatype":"DOUBLE","value":0.0,"timestamp":1458237427279},{"name":"Compressor-2015:Temperature","unit":"1","register":"","datatype":"DOUBLE","value":23554.965268804994,"timestamp":1458237427279},{"name":"Compressor-2015:Velocity","unit":"1","register":"","datatype":"DOUBLE","value":636.0512370633045,"timestamp":1458237427279}]
2016-03-17T18:57:07.30+0100 [App/0]      OUT java.lang.NullPointerException: null
2016-03-17T18:57:07.30+0100 [App/0]      OUT 	at com.ge.predix.solsvc.dataingestion.handler.TimeSeriesDataIngestionHandler.handleData(TimeSeriesDataIngestionHandler.java:79)

....

```

This is an extract for the [dataingestion_service_log](https://forum.predix.io/storage/attachments/597-dataingestionlog.txt)

I have this issue **since 3 days** more or less. **last week it worked** with another deployment of the rmd-ref-app - it used v 1.1.3 for machinedata_simulator and of course not the yesterday version  from the rmd-ref-app.

**Comment by gstroup** [comment]
We're seeing this issue also now.  We'll get it fixed as soon as we can.  Thanks.

**Comment by indaco** [comment]
I personally think this is something really important to be fixed and not for me but for everyone wants put their hands on Predix starting with a really good sample like rmd-ref-app

**Comment by gstroup** [comment]
Issue is fixed with recent updates to the app.  Please let us know if you still see any problems.
