### ISSUE TITLE
refApp.py bug

### ISSUE THREAD

**Issue by bkoop87** [PredixDev/predix-rmd-ref-app#7]
Line 701     addAdminUserPolicyGroup(config, group,config.rmdAdmin1Pass)
Line 702     addAdminUserPolicyGroup(config, group,config.rmdUser1Pass)

Should probably be
Line 701     addAdminUserPolicyGroup(config, group,config.rmdAdmin1)
Line 702     addAdminUserPolicyGroup(config, group,config.rmdUser1)

**Comment by gstroup** [comment]
This has been fixed in a new version of the script.  Let us know if you are still seeing a problem.  Thanks.
