### ISSUE TITLE
refAppConfig.py failing with fr_FR locale

### ISSUE THREAD

**Issue by kartben** [PredixDev/predix-rmd-ref-app#9]
My cf CLI spits out logs etc. in French. Therefore when refAppConfig.py tries to e.g parse the "Org:xxxxx" line of the stdout for "cf target", it fails.
Maybe force manually "LANG=en_US.UTF-8" env variable?

**Comment by turnerth** [comment]
Hi Ben,

Can you try adding this to your copy of the script...and if it works we can add it to the instructions.
import locale
locale.setlocale(locale.LC_ALL, 'de_DE')

**Comment by turnerth** [comment]
How'd it go?  did it fix it?  If so, we'll put it in the script.  I don't currently have a french host to try it.  Will to our backlog to get one.

**Comment by kartben** [comment]
I didn't get a chance to try it but I am pretty sure it would work. However, wouldn't it be better to set the local to en_US rather than german?

**Comment by turnerth** [comment]
yeah, i noticed that DE for Deutsch when i posted yesterday.  Wasn't quite sure though and didn't look it up, now I know. Will have one of the engineers try this, in English.

**Comment by turnerth** [comment]
I recall this being added a couple of years back, closing.
